version: 0.1
env:
  variables:
    APP_NAME: CodeDeployGitHubDemo-App
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies... 
      - npm install -g @vue/cli
      - npm install
  build:
    commands:
      - echo Build started on `date` 
      - npm run build
      - cp appspec.yml dist/
artifacts:
  files:
artifacts:
  files:
    - vue.config.js
    - /dist/index.html
    - package.json
    - node_modules/*
  base-directory: dist
